///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IOS_EdgeVisClient
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Credentials_Enter recording.
    /// </summary>
    [TestModule("59d11d69-0e0d-40b1-95bd-e00fb4b46934", ModuleType.Recording, 1)]
    public partial class Credentials_Enter : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IOS_EdgeVisClientRepository repository.
        /// </summary>
        public static IOS_EdgeVisClientRepository repo = IOS_EdgeVisClientRepository.Instance;

        static Credentials_Enter instance = new Credentials_Enter();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Credentials_Enter()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Credentials_Enter Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'TestA' on item 'ComDigitalbarriersEdgeVisClient.ViewControllerWrapper.Enter_Username'.", repo.ComDigitalbarriersEdgeVisClient.ViewControllerWrapper.Enter_UsernameInfo, new RecordItemIndex(0));
            repo.ComDigitalbarriersEdgeVisClient.ViewControllerWrapper.Enter_Username.Element.SetAttributeValue("Text", "TestA");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'password' on item 'ComDigitalbarriersEdgeVisClient.ViewControllerWrapper.Enter_PW'.", repo.ComDigitalbarriersEdgeVisClient.ViewControllerWrapper.Enter_PWInfo, new RecordItemIndex(1));
            repo.ComDigitalbarriersEdgeVisClient.ViewControllerWrapper.Enter_PW.Element.SetAttributeValue("Text", "password");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
