///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace IOS_EdgeVisClient
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the IOS_EdgeVisClientRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b8927673-a583-48dd-bb7e-d1a764d6d53d")]
    public partial class IOS_EdgeVisClientRepository : RepoGenBaseFolder
    {
        static IOS_EdgeVisClientRepository instance = new IOS_EdgeVisClientRepository();
        IOS_EdgeVisClientRepositoryFolders.ComDigitalbarriersEdgeVisClientAppFolder _comdigitalbarriersedgevisclient;

        /// <summary>
        /// Gets the singleton class instance representing the IOS_EdgeVisClientRepository element repository.
        /// </summary>
        [RepositoryFolder("b8927673-a583-48dd-bb7e-d1a764d6d53d")]
        public static IOS_EdgeVisClientRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public IOS_EdgeVisClientRepository() 
            : base("IOS_EdgeVisClientRepository", "/", null, 0, false, "b8927673-a583-48dd-bb7e-d1a764d6d53d", ".\\RepositoryImages\\IOS_EdgeVisClientRepositoryb8927673.rximgres")
        {
            _comdigitalbarriersedgevisclient = new IOS_EdgeVisClientRepositoryFolders.ComDigitalbarriersEdgeVisClientAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b8927673-a583-48dd-bb7e-d1a764d6d53d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ComDigitalbarriersEdgeVisClient folder.
        /// </summary>
        [RepositoryFolder("dd7154de-1c9d-495d-aeee-819a38bd25a1")]
        public virtual IOS_EdgeVisClientRepositoryFolders.ComDigitalbarriersEdgeVisClientAppFolder ComDigitalbarriersEdgeVisClient
        {
            get { return _comdigitalbarriersedgevisclient; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class IOS_EdgeVisClientRepositoryFolders
    {
        /// <summary>
        /// The ComDigitalbarriersEdgeVisClientAppFolder folder.
        /// </summary>
        [RepositoryFolder("dd7154de-1c9d-495d-aeee-819a38bd25a1")]
        public partial class ComDigitalbarriersEdgeVisClientAppFolder : RepoGenBaseFolder
        {
            IOS_EdgeVisClientRepositoryFolders.ViewControllerWrapperFolder _viewcontrollerwrapper;
            IOS_EdgeVisClientRepositoryFolders.UIWindowFolder _uiwindow;

            /// <summary>
            /// Creates a new ComDigitalbarriersEdgeVisClient  folder.
            /// </summary>
            public ComDigitalbarriersEdgeVisClientAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComDigitalbarriersEdgeVisClient", "/mobileapp[@title='com.digitalbarriers.EdgeVis-Client']", parentFolder, 30000, null, false, "dd7154de-1c9d-495d-aeee-819a38bd25a1", "")
            {
                _viewcontrollerwrapper = new IOS_EdgeVisClientRepositoryFolders.ViewControllerWrapperFolder(this);
                _uiwindow = new IOS_EdgeVisClientRepositoryFolders.UIWindowFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dd7154de-1c9d-495d-aeee-819a38bd25a1")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dd7154de-1c9d-495d-aeee-819a38bd25a1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ViewControllerWrapper folder.
            /// </summary>
            [RepositoryFolder("acee4ccb-e04d-494a-b921-cb159899d732")]
            public virtual IOS_EdgeVisClientRepositoryFolders.ViewControllerWrapperFolder ViewControllerWrapper
            {
                get { return _viewcontrollerwrapper; }
            }

            /// <summary>
            /// The UIWindow folder.
            /// </summary>
            [RepositoryFolder("737223a8-05fb-4d74-9867-34c51158def7")]
            public virtual IOS_EdgeVisClientRepositoryFolders.UIWindowFolder UIWindow
            {
                get { return _uiwindow; }
            }
        }

        /// <summary>
        /// The ViewControllerWrapperFolder folder.
        /// </summary>
        [RepositoryFolder("acee4ccb-e04d-494a-b921-cb159899d732")]
        public partial class ViewControllerWrapperFolder : RepoGenBaseFolder
        {
            RepoItemInfo _click_manageInfo;
            RepoItemInfo _enter_usernameInfo;
            RepoItemInfo _click_editInfo;
            RepoItemInfo _enter_pwInfo;
            RepoItemInfo _save_clickInfo;
            RepoItemInfo _connect_clickInfo;
            RepoItemInfo _enter_pw2Info;
            RepoItemInfo _viewoptions_rightInfo;
            RepoItemInfo _connect2_clickInfo;

            /// <summary>
            /// Creates a new ViewControllerWrapper  folder.
            /// </summary>
            public ViewControllerWrapperFolder(RepoGenBaseFolder parentFolder) :
                    base("ViewControllerWrapper", "form/container[@containertype='LayoutContainer']/container[@caption='']", parentFolder, 30000, null, false, "acee4ccb-e04d-494a-b921-cb159899d732", "")
            {
                _click_manageInfo = new RepoItemInfo(this, "Click_MANAGE", ".//button[@accessibilitylabel='MANAGE']", 30000, null, "17f9765c-a806-4d30-94c1-4f393aa62bba");
                _enter_usernameInfo = new RepoItemInfo(this, "Enter_Username", ".//container[@containertype='LayoutContainer']/container[@caption='']/container/text[3]", 30000, null, "391dced0-92a7-41d6-8057-d06ed86b7e08");
                _click_editInfo = new RepoItemInfo(this, "Click_EDIT", ".//table[@accessibilitylabel='Empty list']//button[@accessibilitylabel='EDIT']", 30000, null, "4332a436-5d1c-4752-a271-d37cb519624d");
                _enter_pwInfo = new RepoItemInfo(this, "Enter_PW", ".//container[@containertype='LayoutContainer']/container[@caption='']/container/text[5]", 30000, null, "5c81302d-ebc1-44c2-a955-5e88d506de11");
                _save_clickInfo = new RepoItemInfo(this, "SAVE_Click", ".//container[@containertype='LayoutContainer']/container[@caption='']/?/?/button[@accessibilitylabel='SAVE']", 30000, null, "2debd706-ad9f-40e9-a32c-f458fae7f286");
                _connect_clickInfo = new RepoItemInfo(this, "CONNECT_Click", ".//table[@accessibilitylabel='Empty list']//button[@accessibilitylabel='CONNECT']", 30000, null, "a6e9e345-e041-44ca-8ba9-a1602b79604c");
                _enter_pw2Info = new RepoItemInfo(this, "Enter_PW2", ".//container[@containertype='LayoutContainer']/container[@caption='']/container/text[4]", 30000, null, "5260859e-5450-4541-9332-a6c4c8b3e4d2");
                _viewoptions_rightInfo = new RepoItemInfo(this, "ViewOptions_Right", ".//button[@accessibilitylabel='HotDog icon enabled']", 30000, null, "376c4848-2451-4889-a12c-48c92b5eaa1f");
                _connect2_clickInfo = new RepoItemInfo(this, "CONNECT2_Click", ".//container[@containertype='LayoutContainer']/container[@caption='']/?/?/button[@accessibilitylabel='CONNECT']", 30000, null, "357480d1-7bc9-4fb1-90e7-a1244548be41");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("acee4ccb-e04d-494a-b921-cb159899d732")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("acee4ccb-e04d-494a-b921-cb159899d732")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Click_MANAGE item.
            /// </summary>
            [RepositoryItem("17f9765c-a806-4d30-94c1-4f393aa62bba")]
            public virtual Ranorex.Button Click_MANAGE
            {
                get
                {
                    return _click_manageInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Click_MANAGE item info.
            /// </summary>
            [RepositoryItemInfo("17f9765c-a806-4d30-94c1-4f393aa62bba")]
            public virtual RepoItemInfo Click_MANAGEInfo
            {
                get
                {
                    return _click_manageInfo;
                }
            }

            /// <summary>
            /// The Enter_Username item.
            /// </summary>
            [RepositoryItem("391dced0-92a7-41d6-8057-d06ed86b7e08")]
            public virtual Ranorex.Text Enter_Username
            {
                get
                {
                    return _enter_usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Enter_Username item info.
            /// </summary>
            [RepositoryItemInfo("391dced0-92a7-41d6-8057-d06ed86b7e08")]
            public virtual RepoItemInfo Enter_UsernameInfo
            {
                get
                {
                    return _enter_usernameInfo;
                }
            }

            /// <summary>
            /// The Click_EDIT item.
            /// </summary>
            [RepositoryItem("4332a436-5d1c-4752-a271-d37cb519624d")]
            public virtual Ranorex.Button Click_EDIT
            {
                get
                {
                    return _click_editInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Click_EDIT item info.
            /// </summary>
            [RepositoryItemInfo("4332a436-5d1c-4752-a271-d37cb519624d")]
            public virtual RepoItemInfo Click_EDITInfo
            {
                get
                {
                    return _click_editInfo;
                }
            }

            /// <summary>
            /// The Enter_PW item.
            /// </summary>
            [RepositoryItem("5c81302d-ebc1-44c2-a955-5e88d506de11")]
            public virtual Ranorex.Text Enter_PW
            {
                get
                {
                    return _enter_pwInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Enter_PW item info.
            /// </summary>
            [RepositoryItemInfo("5c81302d-ebc1-44c2-a955-5e88d506de11")]
            public virtual RepoItemInfo Enter_PWInfo
            {
                get
                {
                    return _enter_pwInfo;
                }
            }

            /// <summary>
            /// The SAVE_Click item.
            /// </summary>
            [RepositoryItem("2debd706-ad9f-40e9-a32c-f458fae7f286")]
            public virtual Ranorex.Button SAVE_Click
            {
                get
                {
                    return _save_clickInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SAVE_Click item info.
            /// </summary>
            [RepositoryItemInfo("2debd706-ad9f-40e9-a32c-f458fae7f286")]
            public virtual RepoItemInfo SAVE_ClickInfo
            {
                get
                {
                    return _save_clickInfo;
                }
            }

            /// <summary>
            /// The CONNECT_Click item.
            /// </summary>
            [RepositoryItem("a6e9e345-e041-44ca-8ba9-a1602b79604c")]
            public virtual Ranorex.Button CONNECT_Click
            {
                get
                {
                    return _connect_clickInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CONNECT_Click item info.
            /// </summary>
            [RepositoryItemInfo("a6e9e345-e041-44ca-8ba9-a1602b79604c")]
            public virtual RepoItemInfo CONNECT_ClickInfo
            {
                get
                {
                    return _connect_clickInfo;
                }
            }

            /// <summary>
            /// The Enter_PW2 item.
            /// </summary>
            [RepositoryItem("5260859e-5450-4541-9332-a6c4c8b3e4d2")]
            public virtual Ranorex.Text Enter_PW2
            {
                get
                {
                    return _enter_pw2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Enter_PW2 item info.
            /// </summary>
            [RepositoryItemInfo("5260859e-5450-4541-9332-a6c4c8b3e4d2")]
            public virtual RepoItemInfo Enter_PW2Info
            {
                get
                {
                    return _enter_pw2Info;
                }
            }

            /// <summary>
            /// The ViewOptions_Right item.
            /// </summary>
            [RepositoryItem("376c4848-2451-4889-a12c-48c92b5eaa1f")]
            public virtual Ranorex.Button ViewOptions_Right
            {
                get
                {
                    return _viewoptions_rightInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ViewOptions_Right item info.
            /// </summary>
            [RepositoryItemInfo("376c4848-2451-4889-a12c-48c92b5eaa1f")]
            public virtual RepoItemInfo ViewOptions_RightInfo
            {
                get
                {
                    return _viewoptions_rightInfo;
                }
            }

            /// <summary>
            /// The CONNECT2_Click item.
            /// </summary>
            [RepositoryItem("357480d1-7bc9-4fb1-90e7-a1244548be41")]
            public virtual Ranorex.Button CONNECT2_Click
            {
                get
                {
                    return _connect2_clickInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CONNECT2_Click item info.
            /// </summary>
            [RepositoryItemInfo("357480d1-7bc9-4fb1-90e7-a1244548be41")]
            public virtual RepoItemInfo CONNECT2_ClickInfo
            {
                get
                {
                    return _connect2_clickInfo;
                }
            }
        }

        /// <summary>
        /// The UIWindowFolder folder.
        /// </summary>
        [RepositoryFolder("737223a8-05fb-4d74-9867-34c51158def7")]
        public partial class UIWindowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _isthefrontendapplicationfromdigitaInfo;
            RepoItemInfo _logouttestaInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new UIWindow  folder.
            /// </summary>
            public UIWindowFolder(RepoGenBaseFolder parentFolder) :
                    base("UIWindow", "form", parentFolder, 30000, null, false, "737223a8-05fb-4d74-9867-34c51158def7", "")
            {
                _isthefrontendapplicationfromdigitaInfo = new RepoItemInfo(this, "IsTheFrontEndApplicationFromDigita", ".//dom[@caption='- Help']/body/div/div//article/section/p[@innertext>'is the front end application']", 30000, null, "af5e69e5-652a-45f0-96f2-3f713caa7f8c");
                _logouttestaInfo = new RepoItemInfo(this, "LogOutTestA", ".//table[@accessibilitylabel='Empty list']/?/?/cell[@accessibilitylabel='Log out TestA']/text[@accessibilitylabel='Log out TestA']", 30000, null, "430a0c44-b239-436e-badc-cdadbcf78a61");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[4]//button[@accessibilitylabel='OK']", 30000, null, "3b045cad-2345-47f0-bddc-820d0095dc73");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("737223a8-05fb-4d74-9867-34c51158def7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("737223a8-05fb-4d74-9867-34c51158def7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IsTheFrontEndApplicationFromDigita item.
            /// </summary>
            [RepositoryItem("af5e69e5-652a-45f0-96f2-3f713caa7f8c")]
            public virtual Ranorex.PTag IsTheFrontEndApplicationFromDigita
            {
                get
                {
                    return _isthefrontendapplicationfromdigitaInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The IsTheFrontEndApplicationFromDigita item info.
            /// </summary>
            [RepositoryItemInfo("af5e69e5-652a-45f0-96f2-3f713caa7f8c")]
            public virtual RepoItemInfo IsTheFrontEndApplicationFromDigitaInfo
            {
                get
                {
                    return _isthefrontendapplicationfromdigitaInfo;
                }
            }

            /// <summary>
            /// The LogOutTestA item.
            /// </summary>
            [RepositoryItem("430a0c44-b239-436e-badc-cdadbcf78a61")]
            public virtual Ranorex.Text LogOutTestA
            {
                get
                {
                    return _logouttestaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LogOutTestA item info.
            /// </summary>
            [RepositoryItemInfo("430a0c44-b239-436e-badc-cdadbcf78a61")]
            public virtual RepoItemInfo LogOutTestAInfo
            {
                get
                {
                    return _logouttestaInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("3b045cad-2345-47f0-bddc-820d0095dc73")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("3b045cad-2345-47f0-bddc-820d0095dc73")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
